void resetaMovimento(int *up, int *down, int *left, int *right);
void movimenta(int cima, int baixo, int esquerda, int direita, float *x, float *y,float velocidadePlayer);
void characterShape(int tMouseX, int tMouseY, float axix, float axiy);
void corrigeMouse(int x, int y,int* tMouseX, int* tMouseY, int gloHght);
void randomPosition(int* x, int* y);
void loadCharacter();
void loadPlayerRight();
void loadPlayerLeft();
void loadPlayerFront();
void loadPlayerBack();
